### PR TITLE
Add support for content selectors and privileges

### PR DESCRIPTION
**Pull request by joshua-rutherford**
@Nosmoht this brings the added methods to the go-nexus-client into the terraform provider.  This is based off the untagged version so I'm not sure you guys want to merge this or wait until a tag is cut.

### CODE REVIEW

**Comment by Nosmoht** [comment]
Hi @joshua-rutherford,

thanks for your support. Looks really great. Could you please add an example of how to use the resources within README.md?

**Comment by Nosmoht** [comment]
I've just released [v0.8.0](https://github.com/datadrivers/go-nexus-client/releases/tag/v0.8.0) of go-client-nexus so can fix the library with that tag.

**Comment by Nosmoht** [comment]
@joshua-rutherford ,

i've updated go.mod files to use the new go-nexus-client. Could you please add a section to README.md to show how to use new resources?

**Comment by Nosmoht** [comment]
@joshua-rutherford could you please add examples to README.md so people know how to use the resources?

**Comment by joshua-rutherford** [comment]
I've updated the readme with initial instructions but only for the content selector type on privilege.  If you need all of them it will take me a bit more.

**Comment by Nosmoht** [comment]
Hi @joshua-rutherford ,

thanks again for your support.

**Pull request merged**
