### PR TITLE
feat: add resource and datasource for SSL truststore

### PR DESCRIPTION
**Pull request by afrimberger**
Managing the SSL truststore is not yet supported by the provider. Hence, the PR :).

### CODE REVIEW

**Comment by chris-ruecker** [comment]
Hi @afrimberger, thank you for your contribution. It lgtm so far, the only thing i noticed missing is the docs for the new resource.

Could you please run `make docs` and add the generated files to the PR?

**Comment by chris-ruecker** [comment]
We have split the ssl retrieval into its own DataSource, called nexus_security_ssl. The truststore resource is now only responsible for managing certificates in the truststore.

**Review by anmoel — APPROVED** [review]
lgtm
lgtm

**Comment by anmoel** [comment]
i will fix the docker tests in a seperated PR

**Pull request merged**
